### ISSUE TITLE
Please publish build for Scala 2.12

### ISSUE THREAD

**Issue by mpartel** [angelcervera/osm4scala#15]
http://dl.bintray.com/angelcervera/maven/com/acervera/osm4scala/ only has builds for Scala 2.10 and 2.11.

**Comment by angelcervera** [comment]
Ok, I hope to do it on Monday/Tuesday after testing.

**Comment by mpartel** [comment]
Thanks! I'm personally OK with 2.11 for the moment, but 2.12 would be nice to have eventually.

**Comment by angelcervera** [comment]
It is necessary to update dependencies:
```
unresolved dependency: com.trueaccord.scalapb#scalapb-runtime_2.12;0.5.43: not found
unresolved dependency: org.scalatest#scalatest_2.12;2.2.6: not found
unresolved dependency: org.scalacheck#scalacheck_2.12;1.12.4: not found
```

**Comment by mpartel** [comment]
Thanks!

**Comment by angelcervera** [comment]
@mpartel Also I created [a group in Gitter to talk](https://gitter.im/osm4scala/talk)

Let me know if you need anything else.

Regards.
