### ISSUE TITLE
Use Float for longitude and latitude.

### ISSUE THREAD

**Issue by angelcervera** [angelcervera/osm4scala#26]
To represent coordinates, Double is used.
Because of the possible size and precision of this data, it is possible to use Float to save space.

**Comment by jjuraszek** [comment]
not good idea - there going to be precision issues with nodes location

**Comment by Synesso** [comment]
I agree. Whilst doubles are wasteful, with floats we could only rely on up to 4 decimal places.

```
@ val f: Float = 179.9999f
f: Float = 179.9999F

@ val f: Float = 179.99999f
f: Float = 179.99998F

@ val f: Float = 179.999999f
f: Float = 180.0F
```

**Comment by angelcervera** [comment]
Thanks to @jjuraszek and @Synesso 
You both save me time analyzing the precision used in the osm data set.
